version: "3.7"
services:
  app:
    image: webdevops/php-apache-dev:8.0
    container_name: php-ct-candidates-app
    depends_on:
      - database
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php-apache2
      SERVICE_TAGS: dev
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    ports:
      - "8080:80"
      - "4435:443"
    networks:
      - ct-candidates-network
  database:
    image: mysql:5.5
    container_name: mysql-ct-candidates-app
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3305:3306"
    volumes:
      - mysql-ct-candidates-data:/var/lib/mysql/
      - ./docker/mysql/entrypoint-initdb:/docker-entrypoint-initdb.d
      - ./docker/configs:/etc/mysql/conf.d
    networks:
      - ct-candidates-network
  phpmyadmin:
    container_name: phpmyadmin-ct-candidates-app
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    volumes:
      - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - '8085:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: guiaa_root
    networks:
      - ct-candidates-network
networks:
  ct-candidates-network:

volumes:
 mysql-ct-candidates-data:
    driver: local

# to log into the running container to execute composer or console commands use  docker exec -it php-apache2-guiaa-app /bin/bash
# to link folders to work you need to install a guess os with wsl a create the link in there (public folder)
# https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers
# add the custom network for vpn compatibility sudo docker network create ctdesarrollo-with-vpn --subnet 10.0.1.0/24